### ISSUE TITLE
Remove inline styles

### ISSUE THREAD

**Issue by joe-lynn** [joe-lynn/github-card#3]

**Comment by joe-lynn** [comment]
Is this necessary? Should they be in the style section of the document or a separate stylesheet?

**Comment by bansavage** [comment]
For now, leave where they are. It's just a simple app for now. Nothing fancy

**Comment by bansavage** [comment]
Ok I lied I will make it clean. Seeing how many there actually are.

**Comment by bansavage** [comment]
Big CSS improvements coming down the pipeline
